// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SandboxCollapseProject9
{
    internal sealed partial class Vsix
    {
        public const string Id = "SandboxCollapseProject9.873a70ad-c3b1-40a8-9497-8998b7d6eae3";
        public const string Name = "SandboxCollapseProject9";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Geiselle Holt (Ada Developers Academy)";
        public const string Tags = "";
    }
}
