// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SandboxCollapseProject9
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SandboxCollapseProject9String = "7ce3b24f-9eb5-48ce-8d24-47fe356d0702";
        public static Guid SandboxCollapseProject9 = new Guid(SandboxCollapseProject9String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuCommand = 0x0100;
    }
}